"""initial

Revision ID: 4aa9f4500e18
Revises: 
Create Date: 2026-04-04 04:58:17.447856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aa9f4500e18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'PROCESSOR', 'TRANSPORTER', 'AUDITOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('wallet_encrypted_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('coffee_type', sa.Enum('ARABICA', 'ROBUSTA', 'BLEND', name='coffee_type'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('origin_farm', sa.String(length=255), nullable=False),
    sa.Column('origin_city', sa.String(length=255), nullable=False),
    sa.Column('origin_state', sa.String(length=2), nullable=False),
    sa.Column('harvest_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('HARVESTED', 'PROCESSING', 'ROASTING', 'IN_TRANSIT', 'DELIVERED', 'CERTIFIED', name='batch_status'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('token_id', sa.String(length=78), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_code'), 'batches', ['code'], unique=True)
    op.create_table('batch_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('HARVEST', 'PROCESSING_START', 'PROCESSING_END', 'PICKUP', 'IN_TRANSIT', 'DELIVERY', 'ROASTING_START', 'ROASTING_END', 'PACKAGING', 'INSPECTION', 'CERTIFICATION', 'NOTE', name='event_type'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_batch_events_batch_id'), 'batch_events', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_events_batch_id'), table_name='batch_events')
    op.drop_table('batch_events')
    op.drop_index(op.f('ix_batches_code'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
